version: "3.8"
services:
  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: "http://backend:5001"
    depends_on:
      - backend

  backend:
    build: ./Backend
    ports:
      - "5001:5001"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin
      DATABASE_NAME: smartjuice
      JWT_SECRET: b7f138391501125fb0eec1e386d509861608e088db5bdd7aaa1a70c82eb6e68fb17a8db6bb70668d7a4a3424264c0868057a8ed356702680c84c5ffd2a512523

    depends_on:
      - db

  db:
    image: mariadb:10.11
    container_name: smartjuice_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: smartjuice
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./Database:/docker-entrypoint-initdb.d
